bot:
  abi_migration_branches:
  - v7
  - v8
  automerge: true
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build_tool: rattler-build
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
test: native_and_emulated
